source_index:
    path:     /
    defaults: { _controller: "FetchBundle:Source:index" }
    methods:  GET

source_show:
    path:     /{id}/show
    defaults: { _controller: "FetchBundle:Source:show" }
    methods:  GET

source_new:
    path:     /new
    defaults: { _controller: "FetchBundle:Source:new" }
    methods:  [GET, POST]

source_edit:
    path:     /{id}/edit
    defaults: { _controller: "FetchBundle:Source:edit" }
    methods:  [GET, POST]

source_delete:
    path:     /{id}/delete
    defaults: { _controller: "FetchBundle:Source:delete" }
    methods:  DELETE
